data:
  input_path: data/inputLearnText.txt

training:
  sequence_length: 64
  epochs: 50
  batch_size: 64
  shuffle: true

model:
  embed_size: 128
  num_heads: 4
  num_layers: 4
  dropout: 0.1

optimizer:
  lr: 0.001
  weight_decay: 0.0

artifacts:
  checkpoints_dir: artifacts/checkpoints
  tokenizers_dir: artifacts/tokenizers
  tokenizer_filename: tokenizer.json

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
